name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Installation
      run: sudo apt-get install -y graphviz
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Lancement graphviz
      run: graphviz1.sh g1
